project_id = "rkfbkpjwdihiphpyjsrc"

[functions.leo-chat]
verify_jwt = false

[functions.neonify-image]
verify_jwt = false

[functions.generate-design]
verify_jwt = false

[functions.get-audio-playback]
verify_jwt = false

[functions.get-user-orders]
verify_jwt = false
